# Generated by Django 4.0 on 2022-02-07 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.TimeField()),
                ('days', models.CharField(max_length=13)),
                ('meeting_id', models.CharField(max_length=42)),
                ('subject', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='user.user')),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
