# Generated by Django 4.0.1 on 2022-01-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='days',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='class',
            name='meeting_id',
            field=models.CharField(max_length=42),
        ),
    ]
