# Generated by Django 4.0.1 on 2022-01-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_days_alter_class_meeting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='start_at',
            new_name='starts_at',
        ),
    ]
