# Generated by Django 4.0.1 on 2022-03-04 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_rename_start_at_class_starts_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='class',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='class',
            name='starts_at',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('allday', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=15)),
                ('url', models.URLField()),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.event'),
            preserve_default=False,
        ),
    ]
