# Generated by Django 4.0.1 on 2022-01-30 06:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forms.models
import utils.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('starts_at', models.DateTimeField()),
                ('exam_name', models.CharField(max_length=100)),
                ('uploading_time', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('question_paper', models.FileField(upload_to=utils.files.filename_generator, validators=[utils.files.document_fileextension_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(related_name='exams', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, upload_to=forms.models.class_filename_generator)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='exams.writtenexam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
