# Generated by Django 4.0.1 on 2022-03-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notebook_data_remove_notebook_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='url',
            field=models.CharField(default='https://www.notion.so/Title1-d2761be65b38457aa2ecb6c49e201e04', max_length=255),
            preserve_default=False,
        ),
    ]
