# Generated by Django 4.0.1 on 2022-03-04 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notebookdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookdatabase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
