# Generated by Django 4.0 on 2022-02-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
