# Generated by Django 4.0.1 on 2022-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='BE/2200001', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
