# Generated by Django 4.0.1 on 2022-01-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_active_alter_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('S', 'Student'), ('T', 'Teacher')], default='S', max_length=2),
        ),
    ]
